image: openjdk:11
 # Copied from Oleg Pahhomovs tutorial
stages:
  - build
  - deploy

build front:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - bookstore-front
  script:
    - npm install
    - npm run build

deploy front:
  stage: deploy
  tags:
    - bookstore-front
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    # This is where 100% copy-paste ends
    - cp -r dist/. ~/front-deployment
    - npm run serve
