image: node:lts-alpine
 #Straight copy-paste from Oleg.
 #ToDo: Basically everything.
stages:
  #- build
  #- test
  - deploy

before_script:
  - npm install

cache:
  stage: deploy
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/

#build bookstore-front:
#  stage: build
#  cache:
#    paths:
#      - .gradle/wrapper
#      - .gradle/caches
#  artifacts:
#    paths:
#      - build/libs
#  tags:
#    - bookstore-front
#  script:
#    - ./gradlew assemble

#test bookstore-front:
#  stage: test
#  tags:
#    - bookstore-front
#  script:
#    - ./gradlew check

#deploy bookstore-front:
  #stage: deploy
  #only:
  #  refs:
  #    - master
  #tags:
  #  - bookstore-front
  #script:
  #  - mkdir -p ~/api-deployment
  #  - rm -rf ~/api-deployment/*
  #  - cp -r build/libs/. ~/api-deployment
  #  - sudo service bookstore-front restart
